### ISSUE TITLE
Working docs

### ISSUE THREAD

**Issue by onknows** [OpenIdentityPlatform/OpenAM-Web-Agents#7]
Are these web agent still valid? Is there an instruction that shows how this web agent can be installed / used? 

When I follow instruction such as  https://backstage.forgerock.com/docs/am/6.5/quick-start-guide/ it just ends with an Internal Server Error without any useful info in error messages to troubleshoot. Not even with debug level.

For example the only thing I see is

```
==> /var/log/httpd/error_log <==
[Wed Jan 13 05:20:51.670210 2021] [amagent:debug] [pid 30098] source/apache/agent.c(864): [client 1.1.1.1:55058] amagent_auth_handler():
[/opt/openam-webagent/web_agents/apache24_agent/bin/../instances/agent_1/config/agent.conf] [440055186]
```

**Comment by maximthomas** [comment]
@onknows Hello, have you tried this https://github.com/OpenIdentityPlatform/OpenAM/wiki/Quick-Start-Guide? 

As an alternative to Web Agent, you can use [OpenIG](https://github.com/OpenIdentityPlatform/OpenIG) as a Gateway, see https://github.com/OpenIdentityPlatform/OpenAM/wiki/How-to-Add-Authorization-and-Protect-Your-Application-With-OpenAM-and-OpenIG-Stack
